# Base configuration
spring:
  application:
    name: strength-hub-api

  # JPA/Hibernate
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate  # never drops data
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 25
          fetch_size: 25
    show-sql: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

app:
  coach:
    secret-key: ${COACH_SECRET_KEY:default-fallback}
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION}  # 1 hour
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION}  # 30 days
    issuer: ${JWT_ISSUER}