# Base configuration
spring:
  application:
    name: strength-hub-api

  # JPA/Hibernate
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: validate  # never drops data
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
        show_sql: false
        jdbc:
          batch_size: 25
          fetch_size: 25
    show-sql: false

# Server Configuration
server:
  port: 8080
  servlet:
    context-path: /

# Management endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: when-authorized

app:
  jwt:
    secret: ${JWT_SECRET}
    access-token-expiration-ms: ${JWT_ACCESS_EXPIRATION}
    refresh-token-expiration-ms: ${JWT_REFRESH_EXPIRATION}
    issuer: ${JWT_ISSUER}
    sliding-refresh-days: ${JWT_SLIDING_REFRESH_DAYS}
    max-refresh-tokens-per-user: ${JWT_MAX_REFRESH_TOKENS_PER_USER}
  admin:
    username: ${ADMIN_USERNAME}
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}
    first-name: ${ADMIN_FIRST_NAME}
    last-name: ${ADMIN_LAST_NAME}
  demo:
    enabled: ${DEMO_USERS_ENABLED:false}
    lifter:
      username: ${DEMO_LIFTER_USERNAME}
      email: ${DEMO_LIFTER_EMAIL}
      password: ${DEMO_LIFTER_PASSWORD}
      first-name: ${DEMO_LIFTER_FIRST_NAME}
      last-name: ${DEMO_LIFTER_LAST_NAME}
    coach:
      username: ${DEMO_COACH_USERNAME}
      email: ${DEMO_COACH_EMAIL}
      password: ${DEMO_COACH_PASSWORD}
      first-name: ${DEMO_COACH_FIRST_NAME}
      last-name: ${DEMO_COACH_LAST_NAME}
      bio: ${DEMO_COACH_BIO}
      certifications: ${DEMO_COACH_CERTIFICATIONS}